// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trace.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APITrace struct {
	TraceID              uint64            `protobuf:"varint,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
	Spans                []*Span           `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	StartTime            int64             `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64             `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Baggage              map[string]string `protobuf:"bytes,8,rep,name=baggage,proto3" json:"baggage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *APITrace) Reset()         { *m = APITrace{} }
func (m *APITrace) String() string { return proto.CompactTextString(m) }
func (*APITrace) ProtoMessage()    {}
func (*APITrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_0571941a1d628a80, []int{0}
}

func (m *APITrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APITrace.Unmarshal(m, b)
}
func (m *APITrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APITrace.Marshal(b, m, deterministic)
}
func (m *APITrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APITrace.Merge(m, src)
}
func (m *APITrace) XXX_Size() int {
	return xxx_messageInfo_APITrace.Size(m)
}
func (m *APITrace) XXX_DiscardUnknown() {
	xxx_messageInfo_APITrace.DiscardUnknown(m)
}

var xxx_messageInfo_APITrace proto.InternalMessageInfo

func (m *APITrace) GetTraceID() uint64 {
	if m != nil {
		return m.TraceID
	}
	return 0
}

func (m *APITrace) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *APITrace) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *APITrace) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *APITrace) GetBaggage() map[string]string {
	if m != nil {
		return m.Baggage
	}
	return nil
}

func init() {
	proto.RegisterType((*APITrace)(nil), "pb.APITrace")
	proto.RegisterMapType((map[string]string)(nil), "pb.APITrace.BaggageEntry")
}

func init() {
	proto.RegisterFile("trace.proto", fileDescriptor_0571941a1d628a80)
}

var fileDescriptor_0571941a1d628a80 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4a, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x2a, 0x2e, 0x48,
	0xcc, 0x83, 0xf0, 0x95, 0xde, 0x32, 0x72, 0x71, 0x38, 0x06, 0x78, 0x86, 0x80, 0x94, 0x08, 0x49,
	0x70, 0xb1, 0x83, 0xd5, 0x7a, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0xc1, 0xb8, 0x42,
	0x72, 0x5c, 0xac, 0x20, 0x4d, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x1c, 0x7a, 0x05,
	0x49, 0x7a, 0xc1, 0x05, 0x89, 0x79, 0x41, 0x10, 0x61, 0x21, 0x19, 0x2e, 0xce, 0xe2, 0x92, 0xc4,
	0xa2, 0x92, 0x90, 0xcc, 0xdc, 0x54, 0x09, 0x36, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x84, 0x00, 0xc8,
	0xdc, 0xd4, 0xbc, 0x14, 0xb0, 0x1c, 0x3b, 0x58, 0x0e, 0xc6, 0x15, 0x32, 0xe6, 0x62, 0x4f, 0x4a,
	0x4c, 0x4f, 0x4f, 0x4c, 0x4f, 0x95, 0xe0, 0x00, 0x9b, 0x2c, 0x09, 0x32, 0x19, 0xe6, 0x20, 0x3d,
	0x27, 0x88, 0x9c, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x4c, 0xa5, 0x94, 0x15, 0x17, 0x0f, 0xb2,
	0x84, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0x25, 0xd8, 0xc9, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08,
	0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x13, 0x58, 0x0c, 0xc2, 0xb1, 0x62, 0xb2, 0x60,
	0x4c, 0x62, 0x03, 0x7b, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x79, 0x7e, 0x6f, 0x15,
	0x01, 0x00, 0x00,
}
